### ISSUE TITLE
custom wda bundle id doesn't work

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios-connector#18]
We removed bundleid, testbundleid and xctestconfig as go ios declared that it can detect it automatically. 
Today it was discovered that it is not valid and if nothing is specified then default bundle id `com.facebook...` is used which is wrong.

That's valid comand to start wda:
```
ios runwda \
    --bundleid="$WDA_BUNDLEID" --testrunnerbundleid="$WDA_BUNDLEID" --xctestconfig=WebDriverAgentRunner.xctest \
    --env USE_PORT="$WDA_PORT" \
    --env MJPEG_SERVER_PORT="$MJPEG_PORT" \
    --env UITEST_DISABLE_ANIMATIONS=YES \
    --udid="$DEVICE_UDID" > "${WDA_LOG_FILE}" 2>&1 &
```

but xctestconfig differs for tvOS, so we have to handle TV case and define better strategy to identify bundle id

**Comment by dhreben** [comment]
Tested on prod by Vadim
