### ISSUE TITLE
let's do `exit 0` if mounting failed

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios-connector#2]
https://github.com/zebrunner/mcloud-ios-connector/blob/06c97f038b59bed3a14a93e90b3a9bc346ad716d/entrypoint.sh#L63

there is no sense to exit with error code and initiate automatic restart if mounting is broken. Let's do `exit 0` instead as human review is needed in this case

**Comment by azarouski** [comment]
[fixed](https://github.com/zebrunner/mcloud-ios-connector/commit/6525990d1c1cea0692b897890096a9f877c07bb1)

**Comment by dhreben** [comment]
Verified
