### ISSUE TITLE
add verification for accessibility of the USBMUXD_SOCKET_ADDRESS

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios-connector#21]
https://github.com/zebrunner/mcloud-ios-connector/blob/bd16adbb843cb5e5be5e80ff4ef5371bca99108f/entrypoint.sh#L20
in case of any mistake in mcloud-agent for STF_PROVIDER_HOST and/or USBMUXD_SOCKET_ADDRESS we don't provide valid error message and start socat for unworkable address.

So let's add validation of the USBMUXD_SOCKET_ADDRESS trying to nc. In case of any problem think about several retries/timeout and exit 0 with apprpriate message

**Comment by dhreben** [comment]
implemented:
- public.ecr.aws/zebrunner/mcloud-ios-connector:1.0.2-beta1

**Comment by dhreben** [comment]
Verified. Basic acceptance successfully completed. Video, screenshots and logs are available.

Opened relevant ticket https://github.com/zebrunner/mcloud-ios-connector/issues/28
