### ISSUE TITLE
let's make 2222 as default usbmuxd listening port

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios-connector#3]
https://github.com/zebrunner/mcloud-ios-connector/blob/06c97f038b59bed3a14a93e90b3a9bc346ad716d/entrypoint.sh#L14

22 is ssh and on the mac we reused 2222 already. let's make it a default as weill inside the connector image

**Comment by azarouski** [comment]
[fixed](https://github.com/zebrunner/mcloud-ios-connector/commit/936646ead0d366405e5058c554ed4e74bb37afab)

**Comment by dhreben** [comment]
Verified.
